# Generated by Django 2.2.5 on 2020-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudouser',
            name='raiting',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
