# Generated by Django 2.2.5 on 2020-02-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0002_pseudouser_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.CharField(max_length=200)),
                ('user_contact', models.CharField(max_length=200)),
                ('username_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pull.PseudoUser')),
            ],
        ),
    ]
